import SeverityBadge from './SeverityBadge'
const icons = { FIRE: '🔥', FLOOD: '🌊', EARTHQUAKE: '🏚️', ACCIDENT: '🚑', MEDICAL: '🩹', STORM: '⛈️', LANDSLIDE: '⛰️', CRIME: '⚠️', MENTAL_HEALTH: '💙', OTHER: '⚠️', UNKNOWN: '❔' }
export default function EmergencyAnalysis({ analysis }) {
  if (!analysis) return <section className="rounded-3xl border border-dashed border-slate-700 bg-slate-900/50 p-6 text-center"><div className="text-4xl">🛟</div><h2 className="mt-4 font-semibold">Emergency analysis</h2><p className="mt-2 text-sm leading-6 text-slate-400">Send a message to see the AI's type, severity, confidence, and recommended actions here.</p></section>
  const confidence = Math.round(Number(analysis.confidence || 0) * 100)
  return <section className="overflow-hidden rounded-3xl border border-white/10 bg-slate-900/70 shadow-xl shadow-slate-950/20"><div className="border-b border-white/10 bg-gradient-to-r from-red-500/20 to-transparent px-6 py-5"><p className="text-xs font-bold tracking-[.18em] text-red-300">EMERGENCY ANALYSIS</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-3"><span className="text-3xl">{icons[analysis.emergencyType] || '⚠️'}</span><div><p className="text-xs text-slate-400">Detected type</p><h2 className="font-bold tracking-wide">{analysis.emergencyType}</h2></div></div><SeverityBadge severity={analysis.severity}/></div></div>
    <div className="space-y-5 p-6"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Assessment</p><p className="mt-2 text-sm leading-6 text-slate-200">{analysis.summary}</p></div><div><div className="flex justify-between text-xs"><span className="font-semibold text-slate-300">AI confidence</span><span className="text-cyan-300">{confidence}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-700"><div className="h-full rounded-full bg-cyan-400 transition-all duration-700" style={{ width: `${confidence}%` }}/></div></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Immediate actions</p><ol className="mt-3 space-y-3">{analysis.immediateActions?.map((action, i) => <li key={action} className="flex gap-3 text-sm leading-5 text-slate-200"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-red-500/20 text-xs font-bold text-red-300">{i + 1}</span>{action}</li>)}</ol></div><div className="rounded-xl border border-cyan-300/15 bg-cyan-400/5 p-4 text-sm leading-6 text-cyan-50"><span className="font-semibold text-cyan-300">Additional advice: </span>{analysis.additionalAdvice}</div></div>
  </section>
}
